# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cam2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import vd1_rc
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2 
import numpy as np
from ultilities import (
    get_contours,
    warp_image,
    calculate_distance,
    getOrientation
)
w_a4 = 297
h_a4 = 245
scale = 1

class VideoThread(QtCore.QThread):
    frame_signal = QtCore.pyqtSignal(QtGui.QImage)
    frame_signal_b = QtCore.pyqtSignal(QtGui.QImage)

    def __init__(self):
        super().__init__()
        self.cap = cv2.VideoCapture(1)
        self.running = False
        self.angle = 0.0
        self.length = float(0.0)
        self.width = float(0.0)
    def run(self):
        self.running = True
        while self.running:
            ret, frame = self.cap.read()
            if ret:
                rgb_image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                h, w, ch = rgb_image.shape
                bytes_per_line = ch * w
                qt_image = QtGui.QImage(rgb_image.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
                self.frame_signal.emit(qt_image)

            contours = get_contours(frame,(100,200),50000,show_canny=False)

            if len(contours) != 0:
                biggest_rect = contours[0][1] # approx corners
                warp_img = warp_image(frame, biggest_rect, width=scale * w_a4, height=scale * h_a4)
                contours2 = get_contours(
                warp_img,
                canny_threshold=(100, 200),
                min_area=500,
                draw_cont=False,
                show_canny=False,)
                box = contours2[0][2]

                if len(contours2) != 0:
                    for cont in contours2:
                        self.length = calculate_distance(box[0],box[1]) - 15
                        self.width = calculate_distance(box[0],box[3]) - 10
                        x,y,w,h = cv2.boundingRect(cont[1])
                        # display dimension of obj
                        self.angle = getOrientation(cont[3],warp_img)

                        cv2.putText(
                        warp_img,
                        f"{int(self.length)} mm",
                        (x + w // 2, y - 10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        fontScale=0.6,
                        color=(0, 0, 255),
                        thickness=2,
                        )
                        cv2.putText(
                            warp_img,
                            f"{int(self.width)} mm",
                            (x - 70, y + h // 2),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            fontScale=0.6,
                            color=(0, 0, 255),
                            thickness=2,
                        )
                warp_img = cv2.cvtColor(warp_img,cv2.COLOR_BGR2RGB)
                h,w,ch = warp_img.shape
                qt_warp = QtGui.QImage(warp_img.data, w, h,ch*w, QtGui.QImage.Format_RGB888)
                self.frame_signal_b.emit(qt_warp)
        self.cap.release()

    def stop(self):
        self.running = False
        self.wait()
        
        

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1105, 887)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("border-image: url(:/pic/ds.jpg);")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(570, 250, 521, 421))
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("before")

        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 0, 1111, 192))
        self.textBrowser_4.setStyleSheet("border-image: url(:/pic/logo-scaled.jpg);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(210, 720, 150, 50))
        self.textBrowser.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(470, 720, 150, 50))
        self.textBrowser_2.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(720, 720, 150, 50))
        self.textBrowser_3.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(260, 680, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setTabletTracking(False)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(2)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(510, 680, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setTabletTracking(False)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(2)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(740, 680, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setTabletTracking(False)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setLineWidth(2)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 521, 421))
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(2)
        self.label_5.setText("")
        self.label_5.setObjectName("after")

        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 800, 671, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.pushButton_4.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.pushButton_5.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("border-image: url(:/pic/Hinh-Nen-Trang-10.jpg);")
        self.pushButton_6.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.pushButton_6)

        self.pushButton_4.clicked.connect(self.start_camera)
        self.pushButton_5.clicked.connect(self.stop_camera)
        self.pushButton_6.clicked.connect(self.save_camera)

        self.camera_thread = VideoThread()
        self.camera_thread.frame_signal.connect(self.update_frame)
        self.camera_thread.frame_signal_b.connect(self.update_frame_b)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Length"))
        self.label_3.setText(_translate("Dialog", "Width"))
        self.label_4.setText(_translate("Dialog", "Orientation"))
        self.pushButton_4.setText(_translate("Dialog", "Start"))
        self.pushButton_5.setText(_translate("Dialog", "Stop"))
        self.pushButton_6.setText(_translate("Dialog", "Save"))

    def closeEvent(self, event):
        self.camera_thread.stop()
        event.accept()

    def start_camera(self):
        # open camera and run the script
        self.camera_thread.start()

    def stop_camera(self):
        self.camera_thread.stop()
        # stop the script

    def save_camera(self):
        self.textBrowser.append(str(self.camera_thread.length))
        self.textBrowser_2.append(str(self.camera_thread.width))
        self.textBrowser_3.append(str(self.camera_thread.angle))
        # save the picture and show the result
        pass

    def update_frame(self,frame):
        pixmap = QtGui.QPixmap.fromImage(frame)
        self.label.setPixmap(pixmap.scaled(self.label.size(), QtCore.Qt.KeepAspectRatio))

    def update_frame_b(self,frame):
        pixmap = QtGui.QPixmap.fromImage(frame)
        self.label_5.setPixmap(pixmap.scaled(self.label_5.size(), QtCore.Qt.KeepAspectRatio))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
